export const IconAutres = require(`./icons/Autres.png`);
export const IconAlimentation = require(`./icons/Alimentation.png`);
export const IconLoisir = require(`./icons/Loisirs.png`);
export const IconSanté = require(`./icons/Santé.png`);
/* const IconTransport = require(`./icons/Transport.png`); */
export const IconVetement = require(`./icons/Vêtements.png`);
export const IconLogement = require(`./icons/Logement.png`);
export const IconBudgetEmpty = require(`./icons/BudgetEmpty.png`);
export const IconBudgetAdd = require(`./icons/BudgetAdd.png`);
